### ISSUE TITLE
[TODO] 3th Week of Jan, 2023

### ISSUE THREAD

**Issue by junsu0925** [junsu0925/Nonlinear#1]
- [ ]  modeling of nonlinear medical diagnostic ultrasound, ch 2
- [ ]  modeling of nonlinear medical diagnostic ultrasound, ch 3
- [ ]  modeling of nonlinear medical diagnostic ultrasound, ch 4
- [ ]  Professor's note
- [ ]  searching for authors related to nonlinear model
